server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:file:~/h2db/testdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    adminUser:
      username: admin
      password: admin
    realmImportFile: baeldung-realm.json

logging:
  level:
    netzbegruenung.keycloak: debug
